name: deep-fish
channels:
  - fastchan
dependencies:
  - fastai=2.5
  - jupyter=1.0
  - pip=21.2
  - python=3.9
  - pip:
    - black[jupyter]==21.11b1
    - defopt==6.1.0
    - fiftyone==0.14.3
    - geopy==2.2.0
    - mlflow==1.21.0
    - pre-commit==2.16.0
    - streamlit==1.2.0
    - streamlit-cropper==0.1.3
