channels:
  - fastchan
dependencies:
  - fastai=2.5
  - pip=21.2
  - python=3.9
  - pip:
    - geopy==2.2.0
    - mlflow==1.21.0
    - streamlit==1.4.0
    - git+https://github.com/yanirs/streamlit-analytics
    - streamlit-cropper==0.2.0
