name: deep-fish
channels:
  - fastchan
dependencies:
  - fastai=2.5
  - jupyter=1.0
  - python=3.9
  - pip:
    - black[jupyter]==21.11b1
    - defopt==6.1.0
    - mlflow==1.21.0
    - pre-commit==2.16.0
